# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import asyncio
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles. 
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("threema_gateway_ffi")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_threema_gateway_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_threema_gateway_ffi_checksum_constructor_simpleapi_new() != 12066:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_threema_gateway_ffi_checksum_constructor_simpleapi_new_with_endpoint() != 3945:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_capabilities() != 14048:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_credits() != 58484:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_id() != 20419:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_pubkey() != 19856:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_send() != 46609:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_free.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rustbuffer_reserve.restype = _UniffiRustBuffer
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFutureDroppedCallbackStruct(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_DROPPED_CALLBACK),
    ]
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_u8.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_u8.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_i8.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_i8.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_u16.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_u16.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_i16.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_i16.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_u32.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_u32.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_i32.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_i32.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_u64.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_u64.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_i64.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_i64.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_f32.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_f32.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_f64.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_f64.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_void.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_cancel_void.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_void.restype = None
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_threema_gateway_ffi_rust_future_free_void.restype = None
_UniffiLib.uniffi_threema_gateway_ffi_fn_clone_simpleapi.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_threema_gateway_ffi_fn_clone_simpleapi.restype = ctypes.c_uint64
_UniffiLib.uniffi_threema_gateway_ffi_fn_free_simpleapi.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_threema_gateway_ffi_fn_free_simpleapi.restype = None
_UniffiLib.uniffi_threema_gateway_ffi_fn_constructor_simpleapi_new.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_threema_gateway_ffi_fn_constructor_simpleapi_new.restype = ctypes.c_uint64
_UniffiLib.uniffi_threema_gateway_ffi_fn_constructor_simpleapi_new_with_endpoint.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_threema_gateway_ffi_fn_constructor_simpleapi_new_with_endpoint.restype = ctypes.c_uint64
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_capabilities.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
)
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_capabilities.restype = ctypes.c_uint64
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_credits.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_credits.restype = ctypes.c_uint64
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_id.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
)
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_id.restype = ctypes.c_uint64
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_pubkey.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
)
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_pubkey.restype = ctypes.c_uint64
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_send.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
)
_UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_send.restype = ctypes.c_uint64
_UniffiLib.ffi_threema_gateway_ffi_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_threema_gateway_ffi_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_threema_gateway_ffi_checksum_constructor_simpleapi_new.argtypes = (
)
_UniffiLib.uniffi_threema_gateway_ffi_checksum_constructor_simpleapi_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_threema_gateway_ffi_checksum_constructor_simpleapi_new_with_endpoint.argtypes = (
)
_UniffiLib.uniffi_threema_gateway_ffi_checksum_constructor_simpleapi_new_with_endpoint.restype = ctypes.c_uint16
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_capabilities.argtypes = (
)
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_capabilities.restype = ctypes.c_uint16
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_credits.argtypes = (
)
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_credits.restype = ctypes.c_uint16
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_id.argtypes = (
)
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_id.restype = ctypes.c_uint16
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_pubkey.argtypes = (
)
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_lookup_pubkey.restype = ctypes.c_uint16
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_send.argtypes = (
)
_UniffiLib.uniffi_threema_gateway_ffi_checksum_method_simpleapi_send.restype = ctypes.c_uint16

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# RustFuturePoll values
_UNIFFI_RUST_FUTURE_POLL_READY = 0
_UNIFFI_RUST_FUTURE_POLL_WAKE = 1

# Stores futures for _uniffi_continuation_callback
_UniffiContinuationHandleMap = _UniffiHandleMap()

_UNIFFI_GLOBAL_EVENT_LOOP = None

"""
Set the event loop to use for async functions

This is needed if some async functions run outside of the eventloop, for example:
    - A non-eventloop thread is spawned, maybe from `EventLoop.run_in_executor` or maybe from the
      Rust code spawning its own thread.
    - The Rust code calls an async callback method from a sync callback function, using something
      like `pollster` to block on the async call.

In this case, we need an event loop to run the Python async function, but there's no eventloop set
for the thread.  Use `uniffi_set_event_loop` to force an eventloop to be used in this case.
"""
def uniffi_set_event_loop(eventloop: asyncio.BaseEventLoop):
    global _UNIFFI_GLOBAL_EVENT_LOOP
    _UNIFFI_GLOBAL_EVENT_LOOP = eventloop

def _uniffi_get_event_loop():
    if _UNIFFI_GLOBAL_EVENT_LOOP is not None:
        return _UNIFFI_GLOBAL_EVENT_LOOP
    else:
        return asyncio.get_running_loop()

# Continuation callback for async functions
# lift the return value or error and resolve the future, causing the async function to resume.
@_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK
def _uniffi_continuation_callback(future_ptr, poll_code):
    (eventloop, future) = _UniffiContinuationHandleMap.remove(future_ptr)
    eventloop.call_soon_threadsafe(_uniffi_set_future_result, future, poll_code)

def _uniffi_set_future_result(future, poll_code):
    if not future.cancelled():
        future.set_result(poll_code)

async def _uniffi_rust_call_async(rust_future, ffi_poll, ffi_complete, ffi_free, lift_func, error_ffi_converter):
    try:
        eventloop = _uniffi_get_event_loop()

        # Loop and poll until we see a _UNIFFI_RUST_FUTURE_POLL_READY value
        while True:
            future = eventloop.create_future()
            ffi_poll(
                rust_future,
                _uniffi_continuation_callback,
                _UniffiContinuationHandleMap.insert((eventloop, future)),
            )
            poll_code = await future
            if poll_code == _UNIFFI_RUST_FUTURE_POLL_READY:
                break

        return lift_func(
            _uniffi_rust_call_with_error(error_ffi_converter, ffi_complete, rust_future)
        )
    finally:
        ffi_free(rust_future)

# Public interface members begin here.


class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

class _UniffiFfiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterString.read(buf) for i in range(count)
        ]

@dataclass
class Capabilities:
    """
    Capabilities of a Threema ID.
"""
    def __init__(self, *, text:bool, image:bool, video:bool, audio:bool, file:bool, other:typing.List[str]):
        self.text = text
        self.image = image
        self.video = video
        self.audio = audio
        self.file = file
        self.other = other
        
        

    
    def __str__(self):
        return "Capabilities(text={}, image={}, video={}, audio={}, file={}, other={})".format(self.text, self.image, self.video, self.audio, self.file, self.other)
    def __eq__(self, other):
        if self.text != other.text:
            return False
        if self.image != other.image:
            return False
        if self.video != other.video:
            return False
        if self.audio != other.audio:
            return False
        if self.file != other.file:
            return False
        if self.other != other.other:
            return False
        return True

class _UniffiFfiConverterTypeCapabilities(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Capabilities(
            text=_UniffiFfiConverterBoolean.read(buf),
            image=_UniffiFfiConverterBoolean.read(buf),
            video=_UniffiFfiConverterBoolean.read(buf),
            audio=_UniffiFfiConverterBoolean.read(buf),
            file=_UniffiFfiConverterBoolean.read(buf),
            other=_UniffiFfiConverterSequenceString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterBoolean.check_lower(value.text)
        _UniffiFfiConverterBoolean.check_lower(value.image)
        _UniffiFfiConverterBoolean.check_lower(value.video)
        _UniffiFfiConverterBoolean.check_lower(value.audio)
        _UniffiFfiConverterBoolean.check_lower(value.file)
        _UniffiFfiConverterSequenceString.check_lower(value.other)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterBoolean.write(value.text, buf)
        _UniffiFfiConverterBoolean.write(value.image, buf)
        _UniffiFfiConverterBoolean.write(value.video, buf)
        _UniffiFfiConverterBoolean.write(value.audio, buf)
        _UniffiFfiConverterBoolean.write(value.file, buf)
        _UniffiFfiConverterSequenceString.write(value.other, buf)

class _UniffiFfiConverterBytes(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative byte string length")
        return buf.read(size)

    @staticmethod
    def check_lower(value):
        try:
            memoryview(value)
        except TypeError:
            raise TypeError("a bytes-like object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def write(value, buf):
        buf.write_i32(len(value))
        buf.write(value)

@dataclass
class RecipientKey:
    """
    A Threema ID's public key (32 bytes).
"""
    def __init__(self, *, bytes:bytes):
        self.bytes = bytes
        
        

    
    def __str__(self):
        return "RecipientKey(bytes={})".format(self.bytes)
    def __eq__(self, other):
        if self.bytes != other.bytes:
            return False
        return True

class _UniffiFfiConverterTypeRecipientKey(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return RecipientKey(
            bytes=_UniffiFfiConverterBytes.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterBytes.check_lower(value.bytes)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterBytes.write(value.bytes, buf)



# ApiError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class ApiError(Exception):
    """
    Errors when interacting with the API.

    This is a flat error type, i.e. variant payloads are not exposed to the
    foreign side. Instead, the `Display` representation is used.
"""
    pass

_UniffiTempApiError = ApiError

class ApiError:  # type: ignore
    """
    Errors when interacting with the API.

    This is a flat error type, i.e. variant payloads are not exposed to the
    foreign side. Instead, the `Display` representation is used.
"""
    
    class Api(_UniffiTempApiError):
        """
        See [`lib::errors::ApiError`].
"""
        def __repr__(self):
            return "ApiError.Api({})".format(repr(str(self)))
    _UniffiTempApiError.Api = Api # type: ignore
    class InvalidThreemaId(_UniffiTempApiError):
        """
        Invalid Threema ID passed from the foreign side.
"""
        def __repr__(self):
            return "ApiError.InvalidThreemaId({})".format(repr(str(self)))
    _UniffiTempApiError.InvalidThreemaId = InvalidThreemaId # type: ignore

ApiError = _UniffiTempApiError # type: ignore
del _UniffiTempApiError


class _UniffiFfiConverterTypeApiError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return ApiError.Api(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 2:
            return ApiError.InvalidThreemaId(
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, ApiError.Api):
            return
        if isinstance(value, ApiError.InvalidThreemaId):
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, ApiError.Api):
            buf.write_i32(1)
        if isinstance(value, ApiError.InvalidThreemaId):
            buf.write_i32(2)






class LookupCriterion:
    """
    Different ways to look up a Threema ID in the directory.
"""
    def __init__(self):
        raise RuntimeError("LookupCriterion cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    @dataclass
    class PHONE:
        """
        The phone number in E.164 format, without the leading `+`.
"""
        
        def __init__(self, phone:str):
            self.phone = phone
            
            
            pass

    
            
            
    
        def __str__(self):
            return "LookupCriterion.PHONE(phone={})".format(self.phone)
        def __eq__(self, other):
            if not isinstance(other, LookupCriterion):
                return NotImplemented
            if not other.is_PHONE():
                return False
            if self.phone != other.phone:
                return False
            return True

    @dataclass
    class PHONE_HASH:
        """
        HMAC-SHA256 hash of the E.164 phone number.
"""
        
        def __init__(self, phone_hash:str):
            self.phone_hash = phone_hash
            
            
            pass

    
            
            
    
        def __str__(self):
            return "LookupCriterion.PHONE_HASH(phone_hash={})".format(self.phone_hash)
        def __eq__(self, other):
            if not isinstance(other, LookupCriterion):
                return NotImplemented
            if not other.is_PHONE_HASH():
                return False
            if self.phone_hash != other.phone_hash:
                return False
            return True

    @dataclass
    class EMAIL:
        """
        The e-mail address.
"""
        
        def __init__(self, email:str):
            self.email = email
            
            
            pass

    
            
            
    
        def __str__(self):
            return "LookupCriterion.EMAIL(email={})".format(self.email)
        def __eq__(self, other):
            if not isinstance(other, LookupCriterion):
                return NotImplemented
            if not other.is_EMAIL():
                return False
            if self.email != other.email:
                return False
            return True

    @dataclass
    class EMAIL_HASH:
        """
        HMAC-SHA256 hash of the lowercased, trimmed e-mail address.
"""
        
        def __init__(self, email_hash:str):
            self.email_hash = email_hash
            
            
            pass

    
            
            
    
        def __str__(self):
            return "LookupCriterion.EMAIL_HASH(email_hash={})".format(self.email_hash)
        def __eq__(self, other):
            if not isinstance(other, LookupCriterion):
                return NotImplemented
            if not other.is_EMAIL_HASH():
                return False
            if self.email_hash != other.email_hash:
                return False
            return True

    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_PHONE(self) -> bool:
        return isinstance(self, LookupCriterion.PHONE)
    def is_phone(self) -> bool:
        return isinstance(self, LookupCriterion.PHONE)
    def is_PHONE_HASH(self) -> bool:
        return isinstance(self, LookupCriterion.PHONE_HASH)
    def is_phone_hash(self) -> bool:
        return isinstance(self, LookupCriterion.PHONE_HASH)
    def is_EMAIL(self) -> bool:
        return isinstance(self, LookupCriterion.EMAIL)
    def is_email(self) -> bool:
        return isinstance(self, LookupCriterion.EMAIL)
    def is_EMAIL_HASH(self) -> bool:
        return isinstance(self, LookupCriterion.EMAIL_HASH)
    def is_email_hash(self) -> bool:
        return isinstance(self, LookupCriterion.EMAIL_HASH)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
LookupCriterion.PHONE = type("LookupCriterion.PHONE", (LookupCriterion.PHONE, LookupCriterion,), {})  # type: ignore
LookupCriterion.PHONE_HASH = type("LookupCriterion.PHONE_HASH", (LookupCriterion.PHONE_HASH, LookupCriterion,), {})  # type: ignore
LookupCriterion.EMAIL = type("LookupCriterion.EMAIL", (LookupCriterion.EMAIL, LookupCriterion,), {})  # type: ignore
LookupCriterion.EMAIL_HASH = type("LookupCriterion.EMAIL_HASH", (LookupCriterion.EMAIL_HASH, LookupCriterion,), {})  # type: ignore




class _UniffiFfiConverterTypeLookupCriterion(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return LookupCriterion.PHONE(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 2:
            return LookupCriterion.PHONE_HASH(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return LookupCriterion.EMAIL(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 4:
            return LookupCriterion.EMAIL_HASH(
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_PHONE():
            _UniffiFfiConverterString.check_lower(value.phone)
            return
        if value.is_PHONE_HASH():
            _UniffiFfiConverterString.check_lower(value.phone_hash)
            return
        if value.is_EMAIL():
            _UniffiFfiConverterString.check_lower(value.email)
            return
        if value.is_EMAIL_HASH():
            _UniffiFfiConverterString.check_lower(value.email_hash)
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_PHONE():
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value.phone, buf)
        if value.is_PHONE_HASH():
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value.phone_hash, buf)
        if value.is_EMAIL():
            buf.write_i32(3)
            _UniffiFfiConverterString.write(value.email, buf)
        if value.is_EMAIL_HASH():
            buf.write_i32(4)
            _UniffiFfiConverterString.write(value.email_hash, buf)








class Recipient:
    """
    Different ways to specify a message recipient in basic mode.
"""
    def __init__(self):
        raise RuntimeError("Recipient cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    @dataclass
    class ID:
        """
        Recipient identity (8 characters).
"""
        
        def __init__(self, id:str):
            self.id = id
            
            
            pass

    
            
            
    
        def __str__(self):
            return "Recipient.ID(id={})".format(self.id)
        def __eq__(self, other):
            if not isinstance(other, Recipient):
                return NotImplemented
            if not other.is_ID():
                return False
            if self.id != other.id:
                return False
            return True

    @dataclass
    class PHONE:
        """
        Recipient phone number (E.164), without leading +.
"""
        
        def __init__(self, phone:str):
            self.phone = phone
            
            
            pass

    
            
            
    
        def __str__(self):
            return "Recipient.PHONE(phone={})".format(self.phone)
        def __eq__(self, other):
            if not isinstance(other, Recipient):
                return NotImplemented
            if not other.is_PHONE():
                return False
            if self.phone != other.phone:
                return False
            return True

    @dataclass
    class EMAIL:
        """
        Recipient e-mail address.
"""
        
        def __init__(self, email:str):
            self.email = email
            
            
            pass

    
            
            
    
        def __str__(self):
            return "Recipient.EMAIL(email={})".format(self.email)
        def __eq__(self, other):
            if not isinstance(other, Recipient):
                return NotImplemented
            if not other.is_EMAIL():
                return False
            if self.email != other.email:
                return False
            return True

    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_ID(self) -> bool:
        return isinstance(self, Recipient.ID)
    def is_id(self) -> bool:
        return isinstance(self, Recipient.ID)
    def is_PHONE(self) -> bool:
        return isinstance(self, Recipient.PHONE)
    def is_phone(self) -> bool:
        return isinstance(self, Recipient.PHONE)
    def is_EMAIL(self) -> bool:
        return isinstance(self, Recipient.EMAIL)
    def is_email(self) -> bool:
        return isinstance(self, Recipient.EMAIL)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
Recipient.ID = type("Recipient.ID", (Recipient.ID, Recipient,), {})  # type: ignore
Recipient.PHONE = type("Recipient.PHONE", (Recipient.PHONE, Recipient,), {})  # type: ignore
Recipient.EMAIL = type("Recipient.EMAIL", (Recipient.EMAIL, Recipient,), {})  # type: ignore




class _UniffiFfiConverterTypeRecipient(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Recipient.ID(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 2:
            return Recipient.PHONE(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return Recipient.EMAIL(
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_ID():
            _UniffiFfiConverterString.check_lower(value.id)
            return
        if value.is_PHONE():
            _UniffiFfiConverterString.check_lower(value.phone)
            return
        if value.is_EMAIL():
            _UniffiFfiConverterString.check_lower(value.email)
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_ID():
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value.id, buf)
        if value.is_PHONE():
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value.phone, buf)
        if value.is_EMAIL():
            buf.write_i32(3)
            _UniffiFfiConverterString.write(value.email, buf)



class _UniffiFfiConverterInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "i64"
    VALUE_MIN = -2**63
    VALUE_MAX = 2**63

    @staticmethod
    def read(buf):
        return buf.read_i64()

    @staticmethod
    def write(value, buf):
        buf.write_i64(value)


class SimpleApiProtocol(typing.Protocol):
    """
    Threema Gateway Simple API (without end-to-end encryption).
"""
    
    async def lookup_capabilities(self, id: str) -> Capabilities:
        """
        Look up the capabilities of a Threema ID.
"""
        raise NotImplementedError
    async def lookup_credits(self, ) -> int:
        """
        Look up remaining gateway credits.
"""
        raise NotImplementedError
    async def lookup_id(self, criterion: LookupCriterion) -> str:
        """
        Look up a Threema ID in the directory by phone number or e-mail.
"""
        raise NotImplementedError
    async def lookup_pubkey(self, id: str) -> RecipientKey:
        """
        Fetch the public key for the specified Threema ID.
"""
        raise NotImplementedError
    async def send(self, to: Recipient,text: str) -> str:
        """
        Send a message to the specified recipient in basic mode.

        Returns the message ID on success.
"""
        raise NotImplementedError

class SimpleApi(SimpleApiProtocol):
    """
    Threema Gateway Simple API (without end-to-end encryption).
"""
    
    _handle: ctypes.c_uint64
    def __init__(self, id: str,secret: str):
        """
        Create a new Simple API instance.
"""
        
        _UniffiFfiConverterString.check_lower(id)

        _UniffiFfiConverterString.check_lower(secret)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(id),
            _UniffiFfiConverterString.lower(secret),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeSimpleApi.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeApiError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_threema_gateway_ffi_fn_constructor_simpleapi_new,
            *_uniffi_lowered_args,
        )
        self._handle = _uniffi_ffi_result
    @classmethod
    def new_with_endpoint(cls, id: str,secret: str,endpoint: str) -> SimpleApi:
        """
        Create a new Simple API instance with a custom endpoint URL.
"""
        
        _UniffiFfiConverterString.check_lower(id)

        _UniffiFfiConverterString.check_lower(secret)

        _UniffiFfiConverterString.check_lower(endpoint)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(id),
            _UniffiFfiConverterString.lower(secret),
            _UniffiFfiConverterString.lower(endpoint),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeSimpleApi.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeApiError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_threema_gateway_ffi_fn_constructor_simpleapi_new_with_endpoint,
            *_uniffi_lowered_args,
        )
        return cls._uniffi_make_instance(_uniffi_ffi_result)

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_threema_gateway_ffi_fn_free_simpleapi, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_threema_gateway_ffi_fn_clone_simpleapi, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    async def lookup_capabilities(self, id: str) -> Capabilities:
        """
        Look up the capabilities of a Threema ID.
"""
        
        _UniffiFfiConverterString.check_lower(id)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(id),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeCapabilities.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeApiError
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_capabilities(*_uniffi_lowered_args),
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_rust_buffer,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_rust_buffer,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_free_rust_buffer,
            _uniffi_lift_return,
            _uniffi_error_converter,
        )
    async def lookup_credits(self, ) -> int:
        """
        Look up remaining gateway credits.
"""
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterInt64.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeApiError
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_credits(*_uniffi_lowered_args),
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_i64,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_i64,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_free_i64,
            _uniffi_lift_return,
            _uniffi_error_converter,
        )
    async def lookup_id(self, criterion: LookupCriterion) -> str:
        """
        Look up a Threema ID in the directory by phone number or e-mail.
"""
        
        _UniffiFfiConverterTypeLookupCriterion.check_lower(criterion)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterTypeLookupCriterion.lower(criterion),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeApiError
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_id(*_uniffi_lowered_args),
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_rust_buffer,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_rust_buffer,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_free_rust_buffer,
            _uniffi_lift_return,
            _uniffi_error_converter,
        )
    async def lookup_pubkey(self, id: str) -> RecipientKey:
        """
        Fetch the public key for the specified Threema ID.
"""
        
        _UniffiFfiConverterString.check_lower(id)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(id),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeRecipientKey.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeApiError
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_lookup_pubkey(*_uniffi_lowered_args),
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_rust_buffer,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_rust_buffer,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_free_rust_buffer,
            _uniffi_lift_return,
            _uniffi_error_converter,
        )
    async def send(self, to: Recipient,text: str) -> str:
        """
        Send a message to the specified recipient in basic mode.

        Returns the message ID on success.
"""
        
        _UniffiFfiConverterTypeRecipient.check_lower(to)

        _UniffiFfiConverterString.check_lower(text)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterTypeRecipient.lower(to),
            _UniffiFfiConverterString.lower(text),
        )
        _uniffi_lift_return = _UniffiFfiConverterString.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeApiError
        return await _uniffi_rust_call_async(
            _UniffiLib.uniffi_threema_gateway_ffi_fn_method_simpleapi_send(*_uniffi_lowered_args),
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_poll_rust_buffer,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_complete_rust_buffer,
            _UniffiLib.ffi_threema_gateway_ffi_rust_future_free_rust_buffer,
            _uniffi_lift_return,
            _uniffi_error_converter,
        )





class _UniffiFfiConverterTypeSimpleApi:
    @staticmethod
    def lift(value: int) -> SimpleApi:
        return SimpleApi._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: SimpleApi):
        if not isinstance(value, SimpleApi):
            raise TypeError("Expected SimpleApi instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: SimpleApi) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> SimpleApi:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: SimpleApi, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

class _UniffiFfiConverterUInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.read_u8()

    @staticmethod
    def write(value, buf):
        buf.write_u8(value)

__all__ = [
    "InternalError",
    "ApiError",
    "LookupCriterion",
    "Recipient",
    "Capabilities",
    "RecipientKey",
    "SimpleApi",
    "SimpleApiProtocol",
]