// This file is @generated by prost-build.
/// Edit an existing message (e.g. a text message or a media message caption).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EditMessage {
    /// Unique ID of the referred message to be edited.
    #[prost(fixed64, tag = "1")]
    pub message_id: u64,
    /// Text (or caption) to update the referred message with. Should be ≤ 6000
    /// bytes.
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
}
/// Remove an existing message.
///
/// Note: This is a soft-security feature at best and it applies a best effort
/// approach, meaning that it relies on some level of good will on the receiving
/// end. A malicious receiver can easily persist a message prior to removal by
/// e.g. making a screenshot, forwarding it, changing the date, explicitly saving
/// it (if it contains media), etc.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMessage {
    /// Unique ID of the referred message to be removed.
    #[prost(fixed64, tag = "1")]
    pub message_id: u64,
}
